### ISSUE TITLE
Implement `Valuable` for Option<T> and `Result<T>`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/valuable#18]
I *believe* both types should just "flatten" the values instead of implementing `Enumerable`.

So, `Some(u32)` => `Value::U32` or `Value::Unit`.

**Comment by taiki-e** [comment]
I completely agree with you about the `Option`.

However, I'm not sure about the `Result`: how do we handle the `Err` variant if the `std` feature is disabled?

**Comment by hawkw** [comment]
I agree that `Option`'s should almost certainly flatten the value. I'm less convinced about `Result` --- if the `Err` side of a `Result` is _not_ a `&(dyn std::error::Err + 'static)`, there's no way for the visitor to know if the value is an `Ok` or an `Err`.

As a (somewhat contrived) example, if I recorded a `Result<usize, usize>`, the visitor would totally lose the information of whether the `Result` was an `Ok` or an `Err`...which may actually be the only information that we actually want to record. 

IMO, `Result`s _should_ be `Enumerable`, so that the information of whether it was `Ok` or `Err` is always retained. But, I could probably be convinced otherwise by a sufficiently good argument...
